CREATE TABLE Roles (
    id_role BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    role_name VARCHAR(255) NOT NULL
);

CREATE TABLE Status (
    id_status BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE User (
    id_user BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    blocked BOOLEAN NOT NULL DEFAULT FALSE,
    roles_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (roles_id) REFERENCES Roles(id_role)
);

CREATE TABLE Post (
    id_post BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    author_id BIGINT UNSIGNED NOT NULL,
    status_id BIGINT UNSIGNED NOT NULL,
    date_uploaded DATETIME NOT NULL DEFAULT NOW(),
    date_changed DATETIME NULL,
    FOREIGN KEY (author_id) REFERENCES User(id_user),
    FOREIGN KEY (status_id) REFERENCES Status(id_status)
);

CREATE TABLE Review (
    id_review BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    rev_quality INT NOT NULL,
    rev_language INT NOT NULL,
    rev_originality INT NOT NULL,
    comment TEXT,
    date_created DATETIME NOT NULL DEFAULT NOW(),
    published BOOLEAN NOT NULL DEFAULT FALSE,
    post_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (post_id) REFERENCES Post(id_post),
    FOREIGN KEY (user_id) REFERENCES User(id_user)
);
